server:
  port: 8080
spring:
  application:
    name : farmacy-microservice
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/farmacy?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username : root
    password : 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka